name: Without release 1
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with: { fetch-depth: 1 }
      - name: "Set up JDK"
        uses: actions/setup-java@v2
        with: { distribution: "temurin", java-version: "17" }
      - name: Build with Gradle
        id: build
        run: "./gradlew setupGithubActions build"
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
            name: Artifacts
            path: |
              forge/build/libs/
              fabric/build/libs/