name: "Build Release"
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with: { fetch-depth: 0 }
      - name: "Set up JDK"
        uses: actions/setup-java@v2
        with: { distribution: "temurin", java-version: "17" }
      - name: Build with Gradle
        uses: burrunan/gradle-cache-action@v1
        id: build
        with:
          arguments: "setupGithubActions build"
          gradle-version: "wrapper"
      - name: "Create a Release"
        id: create_release
        uses: meeDamian/github-release@2.0
        with:
          files: "fabric/build/libs/${{ steps.build.outputs.mod_name }}-fabric-${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}.jar forge/build/libs/${{ steps.build.outputs.mod_name }}-forge-${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}.jar"
          gzip: false
          name: "${{ steps.build.outputs.mod_name }}-${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: v0.0.2
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
            name: Artifacts
            path: |
              forge/build/libs/
              fabric/build/libs/